FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# =========================
# Install build tools
# =========================
RUN apt-get update && apt-get install -y \
    build-essential \
    g++ \
    make \
    cmake \
    gdb \
    git \
    pkg-config \
    \
    # C++ libraries
    libmodbus-dev \
    libjsoncpp-dev \
    \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 8000    
# =========================
# Working directory
# =========================
WORKDIR /app

# Copy toàn bộ source
# COPY . .

# Build library
# RUN cmake -S source -B build && \
#     cmake --build build && \
#     cmake --install build --prefix /usr/local

# =========================
# Default command
# =========================
CMD ["/bin/bash"]